// - Para comentar o codigo.

/**/ /*Serve para comentar 
varias linhas.*/

alert('ola mundo') //- Para aparecer uma mensagem.

console.log() //- função que vai aparecer a msg apenas no console. ele serve para a gente fazer teste no nosso codigo.

typeof(8) //Essa função identifica o tipo > number 

parseInt // - transforma em valor inteiro 

let primeiroNumero = '5'
typeof(primeiroNumero)
>string


typeof(parseInt(primeiroNumero))  > number

parseFloat // - ponto flutuavel 1,1 / 1,2

.length // - Fala a quantidade de itens que tem no elemento ou tamanho





